version: '3'
services:
  citus-coordinator:
    image: citusdata/citus
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - citus-net

  citus-worker-1:
    image: citusdata/citus
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - citus-net

  citus-worker-2:
    image: citusdata/citus
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - citus-net

networks:
  citus-net:
    driver: bridge
